name: Publish plugin artifacts

on:
  push:
    tags:
      - \d+\.\d+\.\d+

permissions:
  contents: write

jobs:
  pack_and_publish:
    name: Pack And Publish
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v3
      - 
        name: Pack plugin
        run: |
          ./pack_and_publish.sh "${{github.ref_name}}"
      - 
        name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bob-openai-explainer.bobplugin
      - 
        name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
            file-path: appcast.json
            commit-msg: "Publish new version: ${{github.ref_name}}"
            github-token: ${{ secrets.GITHUB_TOKEN }}
